# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_auto_20170514_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 14, 12, 40, 13, 822839, tzinfo=utc)),
        ),
    ]
