# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-27 04:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0029_auto_20170514_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', jsignature.fields.JSignatureField(blank=True, null=True, verbose_name='Signature')),
                ('signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Signature date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 27, 4, 50, 33, 542636, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='check',
            name='signature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.AssetSignature'),
            preserve_default=False,
        ),
    ]
