# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0032_auto_20170527_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('destroyed', 'destroyed'), ('lost_missing_stolen', 'lost, missing or stolen')], default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 4, 6, 0, 23, 573245, tzinfo=utc)),
        ),
    ]
