# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0034_auto_20170604_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='approval_signature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approval_signature', to='assets.AssetSignature'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 4, 6, 50, 26, 871477, tzinfo=utc)),
        ),
    ]
