# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 07:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0037_auto_20170604_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='approval_signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_signature', to='assets.AssetSignature'),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 4, 7, 52, 36, 434498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='check',
            name='signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.AssetSignature'),
        ),
    ]
