# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170507_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.BooleanField(default=False),
        ),
    ]
